### ISSUE TITLE
Issue with - TensorBoard 

### ISSUE THREAD

**Issue by ShibaPrasad** [sebp/survival-cnn-estimator#1]
Hi,
I am currently using the TensorFlow 2 and using the code on your GitHub. But I am getting the "Tensorboard Inactive" error at 

# %load_ext tensorboard.notebook
%load_ext tensorboard
%tensorboard --logdir ckpts-mnist-cnn

Would you please help me - how to solve this?

Reusing TensorBoard on port 6006 (pid 49936), started 0:01:07 ago. (Use '!kill 49936' to kill it.)

TensorBoard
INACTIVE
No dashboards are active for the current data set.

**Comment by sebp** [comment]
I'm afraid the code only works with TensorFlow 1, but not version 2.
